image:
- Visual Studio 2017

platform:
  - x86

configuration:
  - Debug
  - Release
  
branches:
  only:
    - CI_InitialIntegration

install:
  - set QTDIR=C:\Qt\5.12.2\msvc2017
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw730\x86_64-w64-mingw32\bin;%PATH%;
  - set QtMsBuild=%APPVEYOR_BUILD_FOLDER%\QtMsBuild

before_build:
  - cmd: echo %APPVEYOR_BUILD_FOLDER%
  - cmd: dir .

after_build:
  - cmd: dir .
